version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: synthetic-data-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend-uploads:/app/uploads
      - backend-synthetic:/app/synthetic
      - backend-logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=INFO
      # GAN Configuration
      - DEFAULT_GAN_MODEL=ctgan
      - GAN_EPOCHS=100
      - USE_GPU=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - synthetic-data-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: synthetic-data-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - synthetic-data-network

volumes:
  backend-uploads:
    driver: local
  backend-synthetic:
    driver: local
  backend-logs:
    driver: local

networks:
  synthetic-data-network:
    driver: bridge